// flow-typed signature: 16bd5550768de9b5408059a03f71af8b
// flow-typed version: <<STUB>>/karma-webpack_v^5.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-webpack/lib' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/karma-webpack/controller' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/karma-webpack/framework' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/karma-webpack/preprocessor' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/karma/plugin' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/karma/validation' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/utils/hash' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/webpack/defaults' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/webpack/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-webpack/lib/index' {
  declare module.exports: $Exports<'karma-webpack/lib'>;
}
declare module 'karma-webpack/lib/index.js' {
  declare module.exports: $Exports<'karma-webpack/lib'>;
}
declare module 'karma-webpack/lib/karma-webpack/controller.js' {
  declare module.exports: $Exports<'karma-webpack/lib/karma-webpack/controller'>;
}
declare module 'karma-webpack/lib/karma-webpack/framework.js' {
  declare module.exports: $Exports<'karma-webpack/lib/karma-webpack/framework'>;
}
declare module 'karma-webpack/lib/karma-webpack/preprocessor.js' {
  declare module.exports: $Exports<'karma-webpack/lib/karma-webpack/preprocessor'>;
}
declare module 'karma-webpack/lib/karma/plugin.js' {
  declare module.exports: $Exports<'karma-webpack/lib/karma/plugin'>;
}
declare module 'karma-webpack/lib/karma/validation.js' {
  declare module.exports: $Exports<'karma-webpack/lib/karma/validation'>;
}
declare module 'karma-webpack/lib/utils/hash.js' {
  declare module.exports: $Exports<'karma-webpack/lib/utils/hash'>;
}
declare module 'karma-webpack/lib/webpack/defaults.js' {
  declare module.exports: $Exports<'karma-webpack/lib/webpack/defaults'>;
}
declare module 'karma-webpack/lib/webpack/plugin.js' {
  declare module.exports: $Exports<'karma-webpack/lib/webpack/plugin'>;
}
