// flow-typed signature: dbfd0635b2fb40fd7ef12463ab54001f
// flow-typed version: <<STUB>>/karma-mocha_v^2.0.1/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-mocha/commitlint.config' {
  declare module.exports: any;
}

declare module 'karma-mocha/gruntfile' {
  declare module.exports: any;
}

declare module 'karma-mocha/lib/adapter' {
  declare module.exports: any;
}

declare module 'karma-mocha/lib' {
  declare module.exports: any;
}

declare module 'karma-mocha/release.config' {
  declare module.exports: any;
}

declare module 'karma-mocha/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-mocha/commitlint.config.js' {
  declare module.exports: $Exports<'karma-mocha/commitlint.config'>;
}
declare module 'karma-mocha/gruntfile.js' {
  declare module.exports: $Exports<'karma-mocha/gruntfile'>;
}
declare module 'karma-mocha/lib/adapter.js' {
  declare module.exports: $Exports<'karma-mocha/lib/adapter'>;
}
declare module 'karma-mocha/lib/index' {
  declare module.exports: $Exports<'karma-mocha/lib'>;
}
declare module 'karma-mocha/lib/index.js' {
  declare module.exports: $Exports<'karma-mocha/lib'>;
}
declare module 'karma-mocha/release.config.js' {
  declare module.exports: $Exports<'karma-mocha/release.config'>;
}
declare module 'karma-mocha/wallaby.js' {
  declare module.exports: $Exports<'karma-mocha/wallaby'>;
}
